const mbtiStyle = [
  {
    unique_id: 0,
    mStyle: "Portuguese Port",
    text: "당신은 포근하고 친근한 성격으로 주변 사람들에게 편안함과 안정감을 느끼게 하는 능력이 있으며, 즐거움을 주는 캐릭터로서 함께 있는 사람들과 즐거운 시간을 만들고 즐기는 것을 좋아합니다. 또한, 따뜻하고 건강한 유쾌한 에너지를 가진 사람으로 인내와 성숙함을 지니고 있어 어려움을 극복하고 성장하는 모습을 보입니다. 또한, 옛스러운 멋과 귀족적인 매력으로 눈에 띄는 존재입니다.",
    wPic: require("./assets/mbti/Portuguese_Port_female.png"),
    mPic: require("./assets/mbti/Portuguese_Port_male.png"),
  },
  {
    unique_id: 1,
    mStyle: "French Champagne",
    text: "당신은 오랫동안 특별한 날을 축하하는 와인처럼 특별하고 세련된 사람으로, 차분하면서도 우아하며, 특별한 순간들을 아름답게 만들어가는 능력이 있습니다. 외면에서는 상쾌하고 활기차 보일 수 있지만, 내면에서는 더욱 깊이 있고 풍부한 면모를 지니고 있습니다. 주변 사람들에게 자연스럽게 기분 좋은 느낌을 주며, 상쾌하면서도 섬세하고 세련된 매력을 지닙니다.",
    wPic: require("./assets/mbti/French_Champagne_female.png"),
    mPic: require("./assets/mbti/French_Champagne_male.png"),
  },
  {
    unique_id: 2,
    mStyle: "Spanish Cava",
    text: "당신은 맑고 화사하며 청량한 성격으로, 다양한 사람들 사이에서 상쾌하고 밝은 분위기를 조성하는 능력이 있습니다. 친근하고 다정한 성격으로, 과도한 꾸밈 없이 자연스럽고 솔직한 모습을 보여주며 주변 사람들과 쉽게 어울리고 조화를 이루는 능력을 가지고 있습니다.",
    wPic: require("./assets/mbti/spanish_cava_female.png"),
    mPic: require("./assets/mbti/spanish_cava_male.png"),
  },
  {
    unique_id: 3,
    mStyle: "Italian Moscato d'Asti",
    text: "당신은 매력적이고 화사하며 사랑 받는 성격을 가지고 있으며, 상쾌하고 밝은 에너지를 느끼게 해주는 사람입니다. 당신의 활기찬 성격과 밝은 에너지로 인해 주변 사람들에게 긍정적인 영향을 끼치며, 자연스러운 따뜻한 에너지를 통해 함께하는 시간을 즐기고 기분 좋은 경험을 선사합니다. 친근하고 다정한 모습으로 사람들과 쉽게 어울리며, 사람들에게 환영받는 친구와 같이 쉽게 다가갈 수 있는 성격입니다.",
    wPic: require("./assets/mbti/Italian_Moscato_d'Asti_female.png"),
    mPic: require("./assets/mbti/Italian_Moscato_d'Asti_male.png"),
  },
  {
    unique_id: 4,
    mStyle: "Californian Chardonnay",
    text: "당신은 다재다능하고 다양한 매력을 지닌 활발하면서도 강건한 성격을 가진 사람입니다. 사회적인 모임과 이벤트를 즐기며, 언제나 다채로운 매력을 지니고 있어서 주변 사람들에게 매번 새로운 매력을 선사할 수 있는 인물입니다. 열정적이고 상쾌하며 활기찬 성격으로, 다양한 상황에서 빠르게 적응하고 다양한 환경에서 잘 살아낼 수 있는 능력을 가지고 있습니다.",
    wPic: require("./assets/mbti/Californian_Chardonnay_female.png"),
    mPic: require("./assets/mbti/Californian_Chardonnay_male.png"),
  },
  {
    unique_id: 5,
    mStyle: "Californian Sauvignon Blanc",
    text: "당신은 밝고 상쾌한 성격을 지닌 사람입니다. 활기차고 경쾌한 성격으로 주변 사람들을 밝게 웃게 하며 즐거운 인물로 인식될 것입니다. 강인한 성격과 함께 따뜻하고 친근한 성격을 갖추어 주변 사람들과 상쾌하고 부드러운 소통을 잘 이루는 사람입니다. 함께 있을 때 자연스럽게 밝은 에너지와 긍정적인 분위기를 전파하며, 상대방들과의 소통에서 흥미로운 대화와 화끈한 농담으로 분위기를 끌어올리는 인물로 주목받을 것입니다.",
    wPic: require("./assets/mbti/Californian_Sauvignon_Blanc_female.png"),
    mPic: require("./assets/mbti/Californian_Sauvignon_Blanc_male.png"),
  },
  {
    unique_id: 6,
    mStyle: "Bordeaux White",
    text: "당신은 섬세하면서도 매력적인 면모를 지니고 있어 주변 사람들에게 긍정적인 인상을 심어주며, 모임과 파티에서 특별한 존재감을 보여줄 것입니다. 상쾌하고 상류층적인 매력으로 사람들에게 기억에 남는 경험을 선사하며, 세련되고 우아한 매력으로 주변을 매료시킬 인물일 것입니다.",
    wPic: require("./assets/mbti/Bordeaux_White_female.png"),
    mPic: require("./assets/mbti/Bordeaux_White_male.png"),
  },
  {
    unique_id: 7,
    mStyle: "Bourgogne Chablis",
    text: "당신은 상쾌하고 활기찬 성격을 가지고 있어 주변 사람들에게 상쾌한 인상을 주며, 독특한 매력과 자연스러운 세련되고 투명한 분위기를 풍기는 사람입니다. 주변 사람들과 함께하는 모든 시간을 즐기며, 자연스럽게 매력적인 맛과 향을 풍기며 봄의 활기를 담은 모습을 보일 것입니다.",
    wPic: require("./assets/mbti/Bourgogne_Chablis_female.png"),
    mPic: require("./assets/mbti/Bourgogne_Chablis_male.png"),
  },
  {
    unique_id: 8,
    mStyle: "German Riesling",
    text: "당신은 자신만의 독특한 매력과 특별한 맛을 가진 매력적인 인물로서 주변 사람들에게 큰 인상을 주며, 화려하고 다채로운 성격을 가지고 있을 것입니다. 세계 무대에서 성공한 팝스타와 같이 다양한 면모와 경험을 지닌 사람일 것입니다. 세련되고 우아한 면모를 가지며, 자신의 존재감과 독특한 특성으로 누구나 인정하게 될 매력적인 인물입니다. 새로운 경험과 모험을 추구하는 모습을 드러내며, 화려한 세계에서 성공을 거두며 주변 사람들을 놀라게 할 것입니다.",
    wPic: require("./assets/mbti/German_Riesling_female.png"),
    mPic: require("./assets/mbti/German_Riesling_male.png"),
  },
  {
    unique_id: 9,
    mStyle: "New Zealand Sauvignon Blanc",
    text: "당신은 활기차고 상쾌한 성격의 사람으로서 경쾌하고 유쾌한 성격을 지니고 있을 것입니다. 새로운 경험과 새로운 사람들과의 만남을 즐기며, 항상 주변 사람들에게 기쁨과 웃음을 전해주는 사교적인 인물입니다. 활발하고 화려한 성격을 상징하며, 항상 주변에 있는 사람들과 재미있는 시간을 보낼 준비가 되어 있습니다. 새로운 도전을 두려워하지 않고 능동적으로 삶을 즐기며, 자신의 긍정적인 에너지로 주변 사람들을 감동시키는 인물입니다.",
    wPic: require("./assets/mbti/New_Zealand_Sauvignon_Blanc_female.png"),
    mPic: require("./assets/mbti/New_Zealand_Sauvignon_Blanc_male.png"),
  },
  {
    unique_id: 10,
    mStyle: "Californian Pinot Noir",
    text: "당신은 활기차고 밝은 성격을 가진 매력적인 인물입니다. 자신만의 스타일과 유니크한 패션을 즐기며 멋쟁이인 모습을 보일 것입니다. 즐겁고 경쾌한 에너지를 가지고 있으며, 붉은 과일과 꽃 향을 연상시키는 상쾌한 매력을 뿜어냅니다. 활발하고 화려한 성격을 가지고 있어 다른 사람들과의 균형을 잘 이루며, 사회적으로 활발하고 인간 관계를 소중히 여기는 타고난 인싸입니다.",
    wPic: require("./assets/mbti/Californian_Pinot_Noir_female.png"),
    mPic: require("./assets/mbti/Californian_Pinot_Noir_male.png"),
  },
  {
    unique_id: 11,
    mStyle: "Californian Cabernet Sauvignon",
    text: "당신은 확고한 신념과 자기 확신을 가지고 있으며, 강렬한 개성과 풍부한 매력으로 주변 사람들에게 큰 인상을 남기고, 명확하고 선명한 성격을 가지면서도 동시에 감성적이고 풍부한 감수성을 지닐 것입니다. 현실적이고 지혜로운 판단력을 가지고 있으면서도 독창적이고 창의적인 면모를 갖추며, 깊이 있는 성격과 흥미로운 개성을 함께 갖춘 인물로 예상됩니다. 자신의 매력을 잘 발휘하고 주변 사람들과의 관계를 잘 이해하며, 인간관계에서도 풍부한 조화를 이루는 인물로서, 사회적으로 활발하고 인간관계를 소중히 여기는 사람입니다.",
    wPic: require("./assets/mbti/Californian_Cabernet_Sauvignon_female.png"),
    mPic: require("./assets/mbti/Californian_Cabernet_Sauvignon_male.png"),
  },
  {
    unique_id: 12,
    mStyle: "Californian Merlot",
    text: "당신은 주변 사람들을 매료시키는 매력적인 면모를 가지고 있을 것으로 예상됩니다. 부드럽고 온화한 성격을 가지고 있어서 주변 사람들과의 관계에서 자연스럽게 상호작용하고 조화롭게 어울리는 능력을 가진 인물입니다. 성장하고 발전하는 데에 열정을 가지고 있으며, 시간이 지남에 따라 더욱 성숙해지고 풍부한 면면을 갖출 것으로 기대됩니다. 주변 사람들과의 관계에서 호흡을 맞추며, 함께 어울리는 데에 능숙하고 상대방과의 조화를 중요시하는 인물일 것입니다.",
    wPic: require("./assets/mbti/Californian_Merlot_female.png"),
    mPic: require("./assets/mbti/Californian_Merlot_male.png"),
  },
  {
    unique_id: 13,
    mStyle: "Italian Barolo",
    text: "당신은 자신의 출신지나 문화를 자랑스러워하고, 이를 자신의 인격과 특성에 반영할 수 있는 사람입니다. 주변 환경이나 경험들을 자신만의 개성으로 잘 표현하며, 다양한 면모를 보여주는 성숙한 매력과 진중한 성격을 가지고 있습니다. 오래가는 지속적인 인내력과 견고한 신념을 가진 자신의 원칙을 중요시하는 사람입니다. ",
    wPic: require("./assets/mbti/Italian_Barolo_female.png"),
    mPic: require("./assets/mbti/Italian_Barolo_male.png"),
  },
  {
    unique_id: 14,
    mStyle: "Italian Barbaresco",
    text: "당신은 우아하고 인상적인 성격을 가지고 있을 것입니다. 세련된 스타일과 고상한 특성을 지니며, 외모와 매력으로 사람들을 끌어들입니다. 섬세한 성격을 지니면서도 다양한 면모를 보이며, 고상한 취미와 취향을 가진 사람입니다. 고상하면서도 활발한 성격을 가지고 있어 상상력과 창의력이 풍부할 것입니다.",
    wPic: require("./assets/mbti/Italian_Barbaresco_female.png"),
    mPic: require("./assets/mbti/Italian_Barbaresco_male.png"),
  },
  {
    unique_id: 15,
    mStyle: "Italian Brunello di Montalcino",
    text: "당신은 강렬하고 개성있는 성격을 가지고 있을 것입니다. 강인하고 풍부한 성격을 지닌 독창적인 사람으로서 자신만의 스타일과 개성을 돋보이게 합니다. 성별에 관계없이 마초적이고 남성성 또는 섹시함이 돋보이는 사람으로 무거워 보일 수 있지만, 강인하고 개성있는 성격 덕분에 이러한 특성들이 독특하고 매력적으로 비춰집니다. 수트나 드레스를 입고 성숙하고 세련된 모습을 보일 것으로 상상됩니다.",
    wPic: require("./assets/mbti/Italian_Brunello_di_montalcino_female.png"),
    mPic: require("./assets/mbti/Italian_Brunello_di_montalcino_male.png"),
  },
  {
    unique_id: 16,
    mStyle: "Italian Chianti",
    text: "당신은 이탈리아 시골에 사는 사람처럼 자연스럽고 쾌활한 성격을 지니며, 다재다능하며 사교적인 성격과 즐거운 에너지를 가지고 있습니다. 당신은 상냥하고 사람들과 어울리기를 좋아하며, 다양한 상황에 잘 어울리는 유연성을 가지고 있고, 친근하고 유쾌한 성격으로 인해 사람들과 잘 어울리고 즐겁게 지내는 모습이 돋보입니다.",
    wPic: require("./assets/mbti/Italian_Chianti_female.png"),
    mPic: require("./assets/mbti/Italian_Chianti_male.png"),
  },
  {
    unique_id: 17,
    mStyle: "Beaujolais Red",
    text: "당신은 활기차고 밝으며 쾌활한 성격을 가진 사람입니다. 유쾌하고 사랑스러운 면모를 지니고 있으며, 상쾌하고 명랑한 성격을 가지고 있습니다. 사람들과 함께 있을 때 항상 즐거운 분위기를 만들어 주며, 항상 적극적으로 타인과 교류하며 다양한 상황에 잘 적응합니다. 이 와인과 같이 프랑스 시골의 남자/여자처럼 자연스럽고 매력적인 성격을 가지고 있으며, 다른 사람들과의 관계에서도 상대방과의 맞춤을 잘 찾아내어 함께 즐거운 시간을 만들어 줄 것으로 예상됩니다.",
    wPic: require("./assets/mbti/Beaujolais_Red_female.png"),
    mPic: require("./assets/mbti/Beaujolais_Red_male.png"),
  },
  {
    unique_id: 18,
    mStyle: "Bordeaux Red",
    text: "당신은 고상하고 우아한 성격을 지닌 사람입니다. 세련되고 우아하지만 동시에 개성과 멋진 매력을 가진 사람으로서 다양한 면모를 지니고 있습니다. 균형 잡힌 성격을 가지고 있으며, 주변 환경에 영향을 받아 특유의 개성과 매력이 더해졌을 것입니다. 또한, 대중적이고 친근한 성격을 가지고 있으면서도 상황에 따라 우아한 면모를 드러낼 수 있습니다. 프랑스의 유서깊은 집안에서 성공한 사업가나 예술가와 같이 고상하면서도 우아한 매력과 개성을 지닌 사람으로 묘사됩니다.",
    wPic: require("./assets/mbti/Bordeaux_Red_female.png"),
    mPic: require("./assets/mbti/Bordeaux_Red_male.png"),
  },
  {
    unique_id: 19,
    mStyle: "Bourgogne Red",
    text: "당신은 우아하고 섬세한 성격을 가진 사람으로서 부드럽고 친절한 면이 강조될 것입니다. 섬세함과 민감성을 지니고 있으며, 고상함과 섬세함을 자아내는 외모와 특성을 가지고 있습니다. 주변 사람들에게 미덕과 우아함을 전달하고, 타인과의 상호작용에서도 조화를 이루며 일관성 있고 안정적인 모습을 보이지만 갈등이나 강한 감정을 피하려는 경향이 있습니다. 프랑스 태생의 예술가, 음악가, 시인과 같이 우아하고 섬세한 성격으로 조화롭고 평온한 환경에서 빛나는 사람으로 묘사됩니다.",
    wPic: require("./assets/mbti/Bourgogne_Red_male.png"),
    mPic: require("./assets/mbti/Bourgogne_Red_female.png"),
  },
  {
    unique_id: 20,
    mStyle: "Argentinian Malbec",
    text: "당신은 강인하고 매혹적인 성격을 가진 매력적인 인물로서 섬세함과 강인함을 동시에 지니고 있습니다. 진취적인 성향과 남미인의 열정과 활력이 돋보이는 모습입니다. 당신은 자신의 의지와 열정으로 주변을 매료시키며, 강인하면서도 섬세한 면모를 지니고 있습니다. 자신의 감정과 목표를 확고히 하며 진취적으로 행동하는 성격으로, 주변 사람들을 인상 깊게 만들고 인기를 얻을 수 있습니다.",
    wPic: require("./assets/mbti/Argentinian_Malbec_female.png"),
    mPic: require("./assets/mbti/Argentinian_Malbec_male.png"),
  },
  {
    unique_id: 21,
    mStyle: "Australian Shiraz",
    text: "당신은 풍부한 개성과 화려한 매력을 가진 독특하고 다채로운 인물입니다. 매료적이고 매혹적인 매력을 가지고 있으며, 온화하면서도 우아한 성격으로 주변 사람들을 끌어들이는 매력이 있습니다. 자기 주장이 강하고 자아를 잘 알고 있으며, 자신의 능력과 매력을 자신있게 발휘합니다. 사회적인 재능과 즐거운 에너지를 가지고 있어 다른 사람들과의 교류에서 화끈한 매력을 품고 있습니다. 호주 쉬라즈와 같이 자유로운 영혼이며 모험을 즐기고 새로운 경험을 추구하는 성격을 가지고 있으며, 독특한 매력으로 주목받는 사람으로 묘사됩니다.",
    wPic: require("./assets/mbti/Australian_Shiraz_female.png"),
    mPic: require("./assets/mbti/Australian_Shiraz_male.png"),
  },
  {
    unique_id: 22,
    mStyle: "Spanish Rioja Red",
    text: "당신은 우아하고 세련된 매력을 가지면서도 동시에 깊이 있는 면모를 지닌 사람으로 묘사됩니다. 중후한 매력을 품고 있으며, 고상한 분위기를 조성하는 성격을 지니고 있습니다.  결단력과 강인한 면모도 당신과 어울리는 특성으로 나타날 것입니다. 경험과 성장을 통해 더욱 세련되고 깊이 있는 면모를 발휘하는 당신은 주변에서 존경받고 인정받는 인물로서 인상을 주는 사람입니다.",
    wPic: require("./assets/mbti/Spanish_Rioja_Red_female.png"),
    mPic: require("./assets/mbti/Spanish_Rioja_Red_male.png"),
  },
];

export default mbtiStyle;
